### ISSUE TITLE
HomebridgeSmartThingsACSkipping devices

### ISSUE THREAD

**Issue by Gthompson98** [0x4a616e/homebridge-smartthings-ac#1]
**Describe Your Problem:**
Plugin installs properly.  Token added to config.  Plugin starts properly.  Plugin finds all my Smartthings devices but skips all of them.

**Logs:**
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Master Bedroom Fan
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device********-****-****-****-************ Living Room Fan
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Samsung Room A/C
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Living Room Fan Winter Mode
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Master Bedroom Fan Winter Mode
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Master Bedroom Fan
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ ********** Hub
7/30/2021, 12:14:08 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Living Room Fan
```
Show the Homebridge logs here, remove any sensitive information.
```

**Plugin Config:**
{
    "accessories": [],
    "platforms": [
        {
            "platform": "HomebridgeSmartThingsAC",
            "token": "********-****-****-****-************",
            "minTemperature": 16,
            "maxTemperature": 30,
            "updateInterval": 15
        }
    ]
}
```json
Show your Homebridge config.json here, remove any sensitive information.
```

**Screenshots:**

**Environment:**

* **Plugin Version**:1.0.6
* **Homebridge Version**: HOOBS 4.0.98
* **Node.js Version**: 
* **NPM Version**: 
* **Operating System**: Raspbian

**Comment by 0x4a616e** [comment]
Hi @Gthompson98 the plug-in currently requires air conditioning devices to have all of the following capabilities:

```
public static readonly requiredCapabilities = [
    'switch',
    'temperatureMeasurement',
    'thermostatCoolingSetpoint',
    'relativeHumidityMeasurement',
    'airConditionerMode',
  ];
```
My best guess is, that one of those capabilities is missing and that the devices could thus not be added. 

Unfortunately it is not possible right now to see from logs, which exact capability is missing. What I could offer is to add some more detailed logging in the next Version so that we can find out what exactly is missing. Some capabilities like `relativeHumidityMeasurement` are not strictly needed and I could then try to make them optional.

You could also run the following command in your terminal (if you're running some sort of Unix) and check what the capabilities of your devices are: `curl -H "Authorization: Bearer YOUR_ACCESS_TOKEN" https://api.smartthings.com/v1/devices`

**Comment by Gthompson98** [comment]
I am guessing it's the humidity measurement that is missing.  It would be great if to add the debugging in the next version.  Really appreciate it.  
I tried executing the command you provided in the terminal but I get the following response;
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>openresty</center>

**Comment by 0x4a616e** [comment]
Did you replace `YOUR_ACCESS_TOKEN ` with your actual access token in the command? I just published a new version that will log what exact capability is missing. And while i was on it, i also made the humidity measurement optional, so maybe it is already working now 🤞

**Comment by Gthompson98** [comment]
That worked!  Below is the log;
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************ Master Bedroom Fan Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************  Living Room Fan Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACRegistering device ********-****-****-****-************ 
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACAdding new accessory: Samsung Room A/C
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACCurrent relative humidity will not be available for device ********-****-****-****-************ 
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACUpdate status every 15 secs
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device 4919aaef-8dae-4690-9aa1-1911c17c1dde Living Room Fan Winter Mode Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************  Master Bedroom Fan Winter Mode Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************  Master Bedroom Fan Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************   Hub Missing capabilities [
  'switch',
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]
7/30/2021, 2:51:37 PMSmartThings Ac BridgeHomebridgeSmartThingsACSkipping device ********-****-****-****-************  Living Room Fan Missing capabilities [
  'temperatureMeasurement',
  'thermostatCoolingSetpoint',
  'airConditionerMode'
]

It really looks like your plugin can be made to work with more generic SmartThings devices than just Samsung AC's.  Perhaps there are generic capabilities that can be used to support more devices.
Those fans that show up are running Bond FW.  I don't have a Bond hub but Smartthings found them via wifi scan.

Thanks for the help!

**Comment by 0x4a616e** [comment]
Glad to hear that! Well, in principle it is possible of course to support other accessories as well, however it won't be as easy as making humidity measurements optional. Fans for example use a different accessory type in HomeKit, so we need to distinguish between ACs and Fans. Not saying it's not possible but it certainly would be a bit of work...

**Comment by Gthompson98** [comment]
Understood.  In the future, would it be possible to add support for temperature readings in DegF in addition to DegC?  Just realized why I've been getting errors for the temperature setting... "ERROR[SmartThings Ac Bridge F714@Samsung Room A/C@@Heating Threshold Temperature] characteristic was supplied illegal value: number 72 exceeded maximum of 30"

**Comment by 0x4a616e** [comment]
Well, that's actually a good point I haven't considered. The current limits will only work correctly for Celsius... I'll create a new ticket for that 👍
